// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: models/quickstart.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BasicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ForceDelay int32 `protobuf:"zigzag32,1,opt,name=force_delay,json=forceDelay,proto3" json:"force_delay,omitempty"`
	ForceRet   int32 `protobuf:"zigzag32,2,opt,name=force_ret,json=forceRet,proto3" json:"force_ret,omitempty"`
}

func (x *BasicRequest) Reset() {
	*x = BasicRequest{}
	mi := &file_models_quickstart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicRequest) ProtoMessage() {}

func (x *BasicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_quickstart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicRequest.ProtoReflect.Descriptor instead.
func (*BasicRequest) Descriptor() ([]byte, []int) {
	return file_models_quickstart_proto_rawDescGZIP(), []int{0}
}

func (x *BasicRequest) GetForceDelay() int32 {
	if x != nil {
		return x.ForceDelay
	}
	return 0
}

func (x *BasicRequest) GetForceRet() int32 {
	if x != nil {
		return x.ForceRet
	}
	return 0
}

type BasicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BasicResponse) Reset() {
	*x = BasicResponse{}
	mi := &file_models_quickstart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicResponse) ProtoMessage() {}

func (x *BasicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_quickstart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicResponse.ProtoReflect.Descriptor instead.
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return file_models_quickstart_proto_rawDescGZIP(), []int{1}
}

var File_models_quickstart_proto protoreflect.FileDescriptor

var file_models_quickstart_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x71, 0x75, 0x69, 0x63, 0x6b,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x22, 0x4c, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x64,
	0x65, 0x6c, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x0a, 0x66, 0x6f, 0x72, 0x63,
	0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f,
	0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x4e, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x69, 0x63, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x2e, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x2e, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x71, 0x75, 0x69, 0x63,
	0x6b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_quickstart_proto_rawDescOnce sync.Once
	file_models_quickstart_proto_rawDescData = file_models_quickstart_proto_rawDesc
)

func file_models_quickstart_proto_rawDescGZIP() []byte {
	file_models_quickstart_proto_rawDescOnce.Do(func() {
		file_models_quickstart_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_quickstart_proto_rawDescData)
	})
	return file_models_quickstart_proto_rawDescData
}

var file_models_quickstart_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_quickstart_proto_goTypes = []any{
	(*BasicRequest)(nil),  // 0: quickstart.BasicRequest
	(*BasicResponse)(nil), // 1: quickstart.BasicResponse
}
var file_models_quickstart_proto_depIdxs = []int32{
	0, // 0: quickstart.BasicService.Request:input_type -> quickstart.BasicRequest
	1, // 1: quickstart.BasicService.Request:output_type -> quickstart.BasicResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_quickstart_proto_init() }
func file_models_quickstart_proto_init() {
	if File_models_quickstart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_quickstart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_models_quickstart_proto_goTypes,
		DependencyIndexes: file_models_quickstart_proto_depIdxs,
		MessageInfos:      file_models_quickstart_proto_msgTypes,
	}.Build()
	File_models_quickstart_proto = out.File
	file_models_quickstart_proto_rawDesc = nil
	file_models_quickstart_proto_goTypes = nil
	file_models_quickstart_proto_depIdxs = nil
}
