name: grafana-intro-to-mltp
volumes:
  grafana:
  postgres:
services:

  basic_server:
    build:
      context: .
      dockerfile: services/basic_service/Dockerfile
    ports:
      - "8080:8080"
      - "6060:6060"

  beyla-basic-server:
    image: grafana/beyla:1.8.4
    pid: "service:basic_server"
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_RAW
      - DAC_READ_SEARCH
      - SYS_PTRACE
      - PERFMON
      - BPF
      - CHECKPOINT_RESTORE
    command:
      - /beyla
      - --config=/configs/config.yaml
    volumes:
      - ./docker/beyla/:/configs

    environment:
      BEYLA_OPEN_PORT: "8080,6060"
      BEYLA_SERVICE_NAMESPACE: "zepto"
      BEYLA_PROMETHEUS_PORT: "9090"
      #BEYLA_BPF_TRACK_REQUEST_HEADERS: "true"
      OTEL_SERVICE_NAME: "beyla-go-basic-server"
      OTEL_EXPORTER_OTLP_TRACES_INSECURE: "true"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://alloy:4317"
    depends_on:
      basic_server:
        condition: service_started

  requester_server:
    build:
      context: .
      dockerfile: services/requester_service/Dockerfile
    ports:
      - "8081:8081"
      - "6061:6061"
    environment:
      BASIC_SERVER_URL: "http://basic_server:8080"
      BASIC_SERVER_GRPC_URL: "basic_server:6060"

  beyla-requester-server:
    image: grafana/beyla:1.8.4
    pid: "service:requester_server"
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_RAW
      - DAC_READ_SEARCH
      - SYS_PTRACE
      - PERFMON
      - BPF
      - CHECKPOINT_RESTORE
    command:
      - /beyla
      - --config=/configs/config.yaml
    volumes:
      - ./docker/beyla/:/configs
    environment:
      BEYLA_OPEN_PORT: "8081,6061"
      BEYLA_SERVICE_NAMESPACE: "zepto"
      BEYLA_PROMETHEUS_PORT: "9090"
      #BEYLA_BPF_TRACK_REQUEST_HEADERS: "true"
      OTEL_SERVICE_NAME: "beyla-go-requester-server"
      OTEL_EXPORTER_OTLP_TRACES_INSECURE: "true"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://alloy:4317"
    depends_on:
      requester_server:
        condition: service_started

  alloy:
    image: grafana/alloy:v1.3.1
    ports:
      - "12347:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
    volumes:
      - "./docker/alloy/config.alloy:/etc/alloy/config.alloy"
      - "./docker/alloy/endpoints.json:/etc/alloy/endpoints.json"
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]

  grafana:
    image: grafana/grafana:11.2.0
    volumes:
      - "./docker/grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app,grafana-pyroscope-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

  tempo:
    image: grafana/tempo:2.6.0
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
      - "55680:55680"
      - "55681:55681"
      - "14250:14250"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - "./docker/tempo/tempo.yaml:/etc/tempo.yaml"

  mimir:
    image: grafana/mimir:2.13.0
    command: [ "-ingester.native-histograms-ingestion-enabled=true", "-config.file=/etc/mimir.yaml" ]
    ports:
      - "9009:9009"
    volumes:
      - "./docker/mimir/mimir.yaml:/etc/mimir.yaml"

  pyroscope:
    image: grafana/pyroscope:1.8.0
    ports:
      - "4040:4040"
    command: [ "server" ]
